// Days from today, for stock that should be nearing (or past) its date.
const inDays = (n) => new Date(Date.now() + n * 86_400_000);

/**
 * The demo shops a visitor can choose between — one per trade StarTrack is
 * pitched at, so the sandbox speaks their vocabulary from the first screen.
 * A pharmacist landing in a supermarket learns nothing about whether this
 * suits them.
 *
 * `depth` is honest about how far each one goes today:
 *   "full"    — the trade's whole workflow is implemented
 *   "catalog" — correct vocabulary, catalog, stock and alerts, but the
 *               trade-specific workflow (rooms, flocks, production runs,
 *               job tickets) is still being built. Say so rather than let
 *               someone discover it.
 */
export const DEMOS = {
  blinds: {
    label: "Window Blinds", group: "Workshop & Trade", depth: "full",
    blurb: "Priced per square metre, cut from rail and fabric you hold in stock.",
    business: "ClearView Blinds",
    branch: { name: "Showroom", address: "31 Awolowo Way, Ikeja" },
    highlight: "A 2m × 1.5m blind consumes rail, fabric and brackets",
    catalog: [
      { name: "Blackout Fabric (metre)", category: "Fabrics", price: 4800, cost: 3200, stock: 90, reorder: 30 },
      { name: "Sheer Day Fabric (metre)", category: "Fabrics", price: 3600, cost: 2400, stock: 65, reorder: 30 },
      { name: "Aluminium Rail (metre)", category: "Tracks & Rails", price: 2500, cost: 1600, stock: 48, reorder: 20 },
      { name: "Bottom Bar (metre)", category: "Tracks & Rails", price: 1400, cost: 850, stock: 40, reorder: 20 },
      { name: "Mounting Bracket", category: "Fittings", price: 700, cost: 380, stock: 160, reorder: 60 },
      { name: "Chain & Control Set", category: "Fittings", price: 1800, cost: 1050, stock: 52, reorder: 25 },
      { name: "Vertical Blind Slat", category: "Blinds", price: 950, cost: 560, stock: 220, reorder: 80 },
      { name: "Installation (per window)", category: "Installation", price: 5000, cost: 1500, stock: 999, reorder: 0 },
      { name: "Site Measurement Visit", category: "Installation", price: 3000, cost: 800, stock: 999, reorder: 0 },
      { name: "Linen Textured Fabric (metre)", category: "Fabrics", price: 5200, cost: 3400, stock: 75, reorder: 30 },
      { name: "Wood Venetian Slat (metre)", category: "Blinds", price: 1600, cost: 950, stock: 140, reorder: 60 },
      { name: "PVC Venetian Slat (metre)", category: "Blinds", price: 1100, cost: 650, stock: 160, reorder: 60 },
      { name: "Roman Blind Fabric (metre)", category: "Fabrics", price: 5600, cost: 3800, stock: 50, reorder: 20 },
      { name: "Curtain Track (metre)", category: "Tracks & Rails", price: 2100, cost: 1300, stock: 60, reorder: 25 },
      { name: "Wand Control", category: "Fittings", price: 1200, cost: 700, stock: 80, reorder: 30 },
      { name: "Cassette Head Rail (metre)", category: "Tracks & Rails", price: 3200, cost: 2100, stock: 35, reorder: 15 },
      { name: "Tieback Hook", category: "Fittings", price: 450, cost: 220, stock: 200, reorder: 80 },
      { name: "Weight Bar (metre)", category: "Fittings", price: 900, cost: 500, stock: 70, reorder: 30 },
      { name: "Curtain Hooks (pack of 50)", category: "Fittings", price: 1500, cost: 900, stock: 40, reorder: 15 },
      { name: "Repair & Adjustment (per window)", category: "Installation", price: 3500, cost: 1000, stock: 999, reorder: 0 },
    ],
    madeToOrder: {
      name: "Roller Blind (made to size)", category: "Blinds", price: 6500,
      bom: [
        { component: "Blackout Fabric (metre)", per: "sqm", factor: 1.1 },
        { component: "Aluminium Rail (metre)", per: "width", factor: 1 },
        { component: "Bottom Bar (metre)", per: "width", factor: 1 },
        { component: "Mounting Bracket", per: "unit", factor: 2 },
        { component: "Chain & Control Set", per: "unit", factor: 1 },
      ],
    },
  },

  electronics: {
    label: "Electronics", group: "Workshop & Trade", depth: "full",
    blurb: "High-value stock where a single unit matters.",
    business: "Bright Tech Store",
    branch: { name: "Main Shop", address: "3 Computer Village, Ikeja" },
    highlight: "Margins visible on every line — staff never see cost",
    catalog: [
      { name: "iPhone 13 128GB", category: "Phones", price: 620000, cost: 545000, stock: 4, reorder: 3 },
      { name: "Samsung A15", category: "Phones", price: 185000, cost: 158000, stock: 11, reorder: 5 },
      { name: "Tecno Spark 20", category: "Phones", price: 128000, cost: 108000, stock: 2, reorder: 6 },
      { name: "HP Pavilion i5", category: "Computers", price: 780000, cost: 690000, stock: 3, reorder: 2 },
      { name: "Wireless Mouse", category: "Accessories", price: 6500, cost: 3800, stock: 40, reorder: 15 },
      { name: "65W USB-C Charger", category: "Accessories", price: 12000, cost: 7200, stock: 26, reorder: 12 },
      { name: "Power Bank 20000mAh", category: "Accessories", price: 22000, cost: 14500, stock: 8, reorder: 10 },
      { name: "Bluetooth Speaker", category: "Audio & TV", price: 35000, cost: 24000, stock: 6, reorder: 4 },
      { name: "43in Smart TV", category: "Audio & TV", price: 295000, cost: 248000, stock: 2, reorder: 2 },
      { name: "Screen Replacement", category: "Repairs", price: 45000, cost: 28000, stock: 999, reorder: 0 },
      { name: "iPhone 14 128GB", category: "Phones", price: 780000, cost: 690000, stock: 3, reorder: 2 },
      { name: "Infinix Note 30", category: "Phones", price: 210000, cost: 178000, stock: 9, reorder: 5 },
      { name: "Dell Inspiron i5", category: "Computers", price: 650000, cost: 570000, stock: 2, reorder: 2 },
      { name: "Lenovo ThinkPad", category: "Computers", price: 720000, cost: 635000, stock: 2, reorder: 2 },
      { name: "Wireless Keyboard", category: "Accessories", price: 8500, cost: 5200, stock: 25, reorder: 10 },
      { name: "HDMI Cable 2m", category: "Accessories", price: 3500, cost: 2000, stock: 60, reorder: 20 },
      { name: "Screen Protector", category: "Accessories", price: 2000, cost: 900, stock: 100, reorder: 40 },
      { name: "Earpiece (wired)", category: "Accessories", price: 3000, cost: 1600, stock: 50, reorder: 20 },
      { name: "32in Smart TV", category: "Audio & TV", price: 165000, cost: 138000, stock: 4, reorder: 3 },
      { name: "Battery Replacement", category: "Repairs", price: 18000, cost: 9000, stock: 999, reorder: 0 },
    ],
  },

  hotel: {
    label: "Hotel & Guest House", group: "Hospitality", depth: "full",
    blurb: "Rooms booked across dates, a heat map of the week, and folios that settle once.",
    business: "Palm Court Hotel",
    branch: { name: "Front Desk", address: "9 Rumuola Road, Port Harcourt" },
    highlight: "14 rooms with guests in house and arrivals due today",
    // Only things the hotel actually STOCKS. Rooms are not stock — see rooms below.
    catalog: [
      { name: "Continental Breakfast", category: "Food & Drinks", price: 6500, cost: 2800, stock: 60, reorder: 20 },
      { name: "Jollof Rice & Chicken", category: "Food & Drinks", price: 8500, cost: 3900, stock: 40, reorder: 15 },
      { name: "Club Sandwich", category: "Food & Drinks", price: 5500, cost: 2400, stock: 30, reorder: 12 },
      { name: "Bottled Water 75cl", category: "Food & Drinks", price: 700, cost: 300, stock: 180, reorder: 60 },
      { name: "Chilled Beer", category: "Food & Drinks", price: 1800, cost: 1100, stock: 96, reorder: 40 },
      { name: "Soft Drink", category: "Food & Drinks", price: 700, cost: 350, stock: 8, reorder: 40 },
      { name: "Laundry (per load)", category: "Laundry", price: 7500, cost: 2200, stock: 999, reorder: 0 },
      { name: "Airport Pickup", category: "Extras", price: 25000, cost: 12000, stock: 999, reorder: 0 },
      { name: "Extra Towels", category: "Extras", price: 2000, cost: 600, stock: 24, reorder: 10 },
      { name: "English Breakfast", category: "Food & Drinks", price: 7500, cost: 3200, stock: 40, reorder: 15 },
      { name: "Grilled Fish & Chips", category: "Food & Drinks", price: 9500, cost: 4200, stock: 25, reorder: 10 },
      { name: "Fruit Platter", category: "Food & Drinks", price: 4500, cost: 1800, stock: 20, reorder: 10 },
      { name: "Fresh Juice", category: "Food & Drinks", price: 1800, cost: 700, stock: 60, reorder: 25 },
      { name: "Bottled Wine", category: "Food & Drinks", price: 15000, cost: 9000, stock: 24, reorder: 10 },
      { name: "Suya Platter", category: "Food & Drinks", price: 6500, cost: 2800, stock: 20, reorder: 8 },
      { name: "Dry Cleaning (per item)", category: "Laundry", price: 4500, cost: 1200, stock: 999, reorder: 0 },
      { name: "Ironing (per item)", category: "Laundry", price: 1500, cost: 400, stock: 999, reorder: 0 },
      { name: "Late Checkout", category: "Extras", price: 10000, cost: 0, stock: 999, reorder: 0 },
      { name: "Room Service Fee", category: "Extras", price: 2000, cost: 0, stock: 999, reorder: 0 },
      { name: "Spa Treatment", category: "Extras", price: 20000, cost: 8000, stock: 999, reorder: 0 },
    ],
    // Rooms are occupied over dates, never sold off a shelf.
    rooms: {
      types: [
        { name: "Standard", rate: 35000, capacity: 2, amenities: ["AC", "TV", "Wi-Fi"] },
        { name: "Deluxe", rate: 55000, capacity: 3, amenities: ["AC", "TV", "Wi-Fi", "Mini bar"] },
        { name: "Executive Suite", rate: 95000, capacity: 4, amenities: ["AC", "TV", "Wi-Fi", "Lounge", "Bath"] },
      ],
      // floor 1 standard, floor 2 deluxe, floor 3 suites
      list: [
        { number: "101", type: "Standard", floor: "1" },
        { number: "102", type: "Standard", floor: "1" },
        { number: "103", type: "Standard", floor: "1" },
        { number: "104", type: "Standard", floor: "1", housekeeping: "out_of_service", note: "AC unit being replaced" },
        { number: "105", type: "Standard", floor: "1" },
        { number: "106", type: "Standard", floor: "1" },
        { number: "201", type: "Deluxe", floor: "2" },
        { number: "202", type: "Deluxe", floor: "2" },
        { number: "203", type: "Deluxe", floor: "2" },
        { number: "204", type: "Deluxe", floor: "2", housekeeping: "dirty" },
        { number: "205", type: "Deluxe", floor: "2" },
        { number: "301", type: "Executive Suite", floor: "3" },
        { number: "302", type: "Executive Suite", floor: "3" },
        { number: "303", type: "Executive Suite", floor: "3" },
      ],
      // Offsets are relative to today, so the heat map always has something on it.
      stays: [
        { room: "101", guest: "Mr Chukwuma Eze", phone: "08031234567", from: -2, to: 2, status: "checked_in", extras: ["Continental Breakfast", "Chilled Beer"] },
        { room: "201", guest: "Mrs Aisha Bello", phone: "08079998888", from: -1, to: 3, status: "checked_in", extras: ["Jollof Rice & Chicken", "Laundry (per load)"] },
        { room: "301", guest: "Dr Tunde Bakare", phone: "08145556677", from: -3, to: 1, status: "checked_in", extras: ["Airport Pickup", "Club Sandwich"] },
        { room: "102", guest: "Ms Ngozi Okonkwo", phone: "08033334444", from: 0, to: 3, status: "booked" },
        { room: "202", guest: "Mr Idris Yusuf", phone: "08022221111", from: 1, to: 4, status: "booked" },
        { room: "303", guest: "Adeyemi Family", phone: "08188887777", from: 2, to: 6, status: "booked" },
        { room: "103", guest: "Mr Peter Obi", phone: "08066665555", from: -6, to: -3, status: "checked_out" },
      ],
    },
  },

  water: {
    label: "Water Factory", group: "Production", depth: "full",
    pending: "Production runs are real — open Production, define a recipe (preform/caps/labels → a bottled pack) and record a run to see raw materials deducted and finished stock credited, leakage included.",
    blurb: "Sachets and bottles, with the raw materials they are made from.",
    business: "AquaPure Table Water",
    branch: { name: "Factory", address: "Km 4 Old Aba Road, Port Harcourt" },
    highlight: "Raw materials and finished goods side by side",
    catalog: [
      { name: "Preform 50cl (piece)", category: "Raw Materials", price: 26, cost: 22, stock: 8000, reorder: 3000 },
      { name: "Bottle Cap (piece)", category: "Raw Materials", price: 5, cost: 4, stock: 9500, reorder: 3000 },
      { name: "Shrink Label (piece)", category: "Raw Materials", price: 4, cost: 3, stock: 2100, reorder: 3000 },
      { name: "Sachet Film (roll)", category: "Raw Materials", price: 32000, cost: 27000, stock: 6, reorder: 4 },
      { name: "Treatment Chemicals (pack)", category: "Raw Materials", price: 18000, cost: 14500, stock: 3, reorder: 4 },
      { name: "Sachet Water (bag of 20)", category: "Sachets", price: 350, cost: 210, stock: 240, reorder: 100 },
      { name: "Bottled Water 50cl (pack of 12)", category: "Bottles", price: 1800, cost: 1150, stock: 96, reorder: 40 },
      { name: "Bottled Water 75cl (pack of 12)", category: "Bottles", price: 2600, cost: 1700, stock: 48, reorder: 30 },
      { name: "19L Dispenser Bottle", category: "Dispensers", price: 4500, cost: 3000, stock: 22, reorder: 15 },
      { name: "Dispenser Refill 19L", category: "Dispensers", price: 1800, cost: 900, stock: 60, reorder: 30 },
      { name: "Preform 75cl (piece)", category: "Raw Materials", price: 34, cost: 28, stock: 6000, reorder: 2500 },
      { name: "Bottle Cap Large (piece)", category: "Raw Materials", price: 6, cost: 5, stock: 7000, reorder: 2500 },
      { name: "Carton Box (piece)", category: "Raw Materials", price: 120, cost: 95, stock: 1500, reorder: 500 },
      { name: "UV Sterilizer Lamp", category: "Raw Materials", price: 45000, cost: 38000, stock: 2, reorder: 2 },
      { name: "Sachet Water (bag of 30)", category: "Sachets", price: 480, cost: 300, stock: 180, reorder: 80 },
      { name: "Bottled Water 100cl (pack of 12)", category: "Bottles", price: 3200, cost: 2200, stock: 60, reorder: 25 },
      { name: "Bottled Water 150cl (pack of 6)", category: "Bottles", price: 2800, cost: 1900, stock: 40, reorder: 20 },
      { name: "19L Dispenser Bottle (returnable deposit)", category: "Dispensers", price: 1000, cost: 0, stock: 30, reorder: 10 },
      { name: "Dispenser Stand", category: "Dispensers", price: 8500, cost: 5500, stock: 10, reorder: 5 },
      { name: "Table Top Dispenser", category: "Dispensers", price: 22000, cost: 16500, stock: 6, reorder: 3 },
    ],
  },

  poultry: {
    label: "Poultry Farm", group: "Production", depth: "full",
    pending: "Batch/flock tracking is real — open Batches, start one, and feed/mortality/harvest against it. No demo batch is pre-seeded, so today's catalog shows feed and produce as plain stock.",
    blurb: "Feed, birds and eggs, with feed running low.",
    business: "Green Acres Poultry",
    branch: { name: "Farm", address: "Ilesa-Akure Road, Osun" },
    highlight: "Feed stock already below its reorder level",
    catalog: [
      { name: "Layer Mash (25kg bag)", category: "Feed", price: 19500, cost: 16800, stock: 8, reorder: 20 },
      { name: "Broiler Starter (25kg bag)", category: "Feed", price: 22000, cost: 19000, stock: 14, reorder: 20 },
      { name: "Grower Feed (25kg bag)", category: "Feed", price: 20500, cost: 17600, stock: 26, reorder: 15 },
      { name: "Crate of Eggs (30)", category: "Eggs", price: 5200, cost: 3400, stock: 88, reorder: 30, expiry: inDays(18) },
      { name: "Cracked Eggs (crate)", category: "Eggs", price: 3200, cost: 3400, stock: 6, reorder: 0, expiry: inDays(10) },
      { name: "Live Broiler (bird)", category: "Birds", price: 9500, cost: 6800, stock: 120, reorder: 40 },
      { name: "Old Layer (spent bird)", category: "Birds", price: 6500, cost: 4200, stock: 34, reorder: 0 },
      { name: "Day-old Chick", category: "Birds", price: 1400, cost: 1050, stock: 0, reorder: 100 },
      { name: "Newcastle Vaccine (vial)", category: "Medication", price: 4800, cost: 3600, stock: 5, reorder: 6, expiry: inDays(40) },
      { name: "Multivitamin Powder", category: "Medication", price: 3500, cost: 2400, stock: 11, reorder: 8, expiry: inDays(150) },
      { name: "Drinker (5L)", category: "Equipment", price: 4200, cost: 2800, stock: 18, reorder: 10 },
      { name: "Finisher Feed (25kg bag)", category: "Feed", price: 21000, cost: 18200, stock: 20, reorder: 15 },
      { name: "Chick Starter Mash (25kg bag)", category: "Feed", price: 20000, cost: 17200, stock: 15, reorder: 15 },
      { name: "Live Layer (bird)", category: "Birds", price: 7500, cost: 5200, stock: 60, reorder: 20 },
      { name: "Point-of-Lay Pullet", category: "Birds", price: 4500, cost: 3200, stock: 40, reorder: 15 },
      { name: "Cracked Maize (25kg bag)", category: "Feed", price: 12000, cost: 9800, stock: 10, reorder: 10 },
      { name: "Gumboro Vaccine (vial)", category: "Medication", price: 5200, cost: 3900, stock: 4, reorder: 6, expiry: inDays(50) },
      { name: "Dewormer (bottle)", category: "Medication", price: 3200, cost: 2200, stock: 9, reorder: 6, expiry: inDays(200) },
      { name: "Feeder (10kg)", category: "Equipment", price: 5200, cost: 3600, stock: 14, reorder: 8 },
      { name: "Egg Tray (pack of 30)", category: "Equipment", price: 250, cost: 150, stock: 300, reorder: 100 },
    ],
  },

  restaurant: {
    label: "Restaurant", group: "Hospitality", depth: "full",
    pending: "A kitchen order-ticket screen is still on the roadmap. Recipes are real, though — try \"Party Jollof & Chicken\" on the till and watch it deplete rice, chicken, stew mix and oil.",
    blurb: "A full menu with the kitchen's own stock behind it.",
    business: "Mama Cass Kitchen",
    branch: { name: "Main Restaurant", address: "40 Adeniran Ogunsanya, Surulere" },
    highlight: "A recipe dish that deducts its own raw materials on sale",
    catalog: [
      { name: "Jollof Rice & Chicken", category: "Mains", price: 5500, cost: 2400, stock: 60, reorder: 20 },
      { name: "Pounded Yam & Egusi", category: "Mains", price: 6500, cost: 2900, stock: 40, reorder: 15 },
      { name: "Fried Rice & Turkey", category: "Mains", price: 7000, cost: 3200, stock: 35, reorder: 15 },
      { name: "Pepper Soup (goat)", category: "Mains", price: 4500, cost: 2100, stock: 25, reorder: 10 },
      { name: "Moi Moi", category: "Sides", price: 1200, cost: 450, stock: 48, reorder: 20 },
      { name: "Plantain (side)", category: "Sides", price: 1000, cost: 380, stock: 55, reorder: 20 },
      { name: "Chapman", category: "Drinks", price: 2000, cost: 800, stock: 40, reorder: 20 },
      { name: "Bottled Water 75cl", category: "Drinks", price: 700, cost: 300, stock: 120, reorder: 48 },
      { name: "Rice (50kg bag)", category: "Mains", price: 78000, cost: 71000, stock: 4, reorder: 3 },
      { name: "Vegetable Oil (25L)", category: "Mains", price: 62000, cost: 55000, stock: 2, reorder: 3 },
      { name: "Chin Chin", category: "Desserts", price: 1500, cost: 600, stock: 30, reorder: 15, expiry: inDays(21) },
      // Raw materials behind the recipe demo item below — a "Raw Materials"
      // category, priced and stocked like any real ingredient delivery.
      { name: "Rice (kg)", category: "Raw Materials", price: 1200, cost: 950, stock: 80, reorder: 30 },
      { name: "Chicken Portion (piece)", category: "Raw Materials", price: 900, cost: 650, stock: 150, reorder: 40 },
      { name: "Tomato Stew Mix (kg)", category: "Raw Materials", price: 1500, cost: 1100, stock: 30, reorder: 10 },
      { name: "Cooking Oil (litre)", category: "Raw Materials", price: 1800, cost: 1400, stock: 20, reorder: 8 },
      { name: "Efo Riro & Amala", category: "Mains", price: 6500, cost: 2900, stock: 30, reorder: 12 },
      { name: "Grilled Chicken & Salad", category: "Mains", price: 6000, cost: 2600, stock: 25, reorder: 10 },
      { name: "Zobo Drink", category: "Drinks", price: 1200, cost: 450, stock: 50, reorder: 20 },
      { name: "Ice Cream Cup", category: "Desserts", price: 1800, cost: 700, stock: 35, reorder: 15 },
      { name: "Onions (kg)", category: "Raw Materials", price: 800, cost: 600, stock: 25, reorder: 10 },
    ],
    // A plain "per unit" recipe — no dimensions, sells in one tap — proving
    // out the restaurant logic: rice, chicken, stew and oil, per plate.
    madeToOrder: {
      name: "Party Jollof & Chicken", category: "Mains", price: 5800,
      bom: [
        { component: "Rice (kg)", per: "unit", factor: 0.15 },
        { component: "Chicken Portion (piece)", per: "unit", factor: 1 },
        { component: "Tomato Stew Mix (kg)", per: "unit", factor: 0.12 },
        { component: "Cooking Oil (litre)", per: "unit", factor: 0.03 },
      ],
    },
  },

  coldroom: {
    label: "Cold Room (Frozen Fish)", group: "Production", depth: "catalog",
    pending: "Cold-chain batches are real — open Cold Room, record a purchase (cartons at a cost) and break one down to see the shrinkage between declared and weighed-out kg logged automatically. No demo batch is pre-seeded, so recording your first one for a product here replaces its plain opening stock below with just that batch's total — exactly like a real cold room's first day on the system.",
    blurb: "Cartons in, kilograms and pieces out, with the shrinkage between them tracked honestly.",
    business: "IcePoint Cold Room",
    branch: { name: "Cold Store", address: "14 Marine Beach Road, Apapa" },
    highlight: "A shrinkage percentage the operator measures, not guesses",
    catalog: [
      { name: "Titus Mackerel", category: "Titus/Mackerel", price: 950, cost: 780, stock: 40, reorder: 15 },
      { name: "Panla (Hake)", category: "Panla", price: 850, cost: 690, stock: 55, reorder: 20 },
      { name: "Croaker", category: "Croaker", price: 1400, cost: 1150, stock: 20, reorder: 10 },
      { name: "Catfish", category: "Catfish", price: 1600, cost: 1300, stock: 15, reorder: 8 },
      { name: "Tilapia", category: "Tilapia", price: 1200, cost: 980, stock: 18, reorder: 8 },
      { name: "Stockfish (Okporoko)", category: "Stockfish", price: 3200, cost: 2600, stock: 6, reorder: 5 },
      { name: "Chicken (whole)", category: "Chicken & Turkey", price: 3800, cost: 3100, stock: 12, reorder: 6 },
      { name: "Turkey (whole)", category: "Chicken & Turkey", price: 8500, cost: 7100, stock: 5, reorder: 4 },
      { name: "Prawns (jumbo)", category: "Prawns & Seafood", price: 4200, cost: 3400, stock: 8, reorder: 5 },
      { name: "Titus Mackerel - Small", category: "Titus/Mackerel", price: 850, cost: 680, stock: 25, reorder: 10 },
      { name: "Titus Mackerel - Jumbo", category: "Titus/Mackerel", price: 1200, cost: 950, stock: 15, reorder: 8 },
      { name: "Panla - Small", category: "Panla", price: 750, cost: 600, stock: 30, reorder: 12 },
      { name: "Croaker - Big", category: "Croaker", price: 1800, cost: 1450, stock: 10, reorder: 5 },
      { name: "Catfish - Jumbo", category: "Catfish", price: 2000, cost: 1650, stock: 8, reorder: 4 },
      { name: "Tilapia - Small", category: "Tilapia", price: 950, cost: 780, stock: 12, reorder: 6 },
      { name: "Stockfish - Small (Okporoko)", category: "Stockfish", price: 2400, cost: 1900, stock: 10, reorder: 5 },
      { name: "Turkey Wings", category: "Chicken & Turkey", price: 3200, cost: 2600, stock: 10, reorder: 5 },
      { name: "Chicken Wings", category: "Chicken & Turkey", price: 2800, cost: 2300, stock: 14, reorder: 6 },
      { name: "Prawns (medium)", category: "Prawns & Seafood", price: 3200, cost: 2600, stock: 10, reorder: 5 },
      { name: "Ice Cream (tub)", category: "Other Frozen", price: 3500, cost: 2600, stock: 12, reorder: 5 },
    ],
  },

  laundry: {
    label: "Laundry & Dry Cleaning", group: "Workshop & Trade", depth: "full",
    blurb: "Drop it off dirty, tracked ticket to ticket, collect it clean.",
    business: "CleanPress Laundromat",
    branch: { name: "Main Outlet", address: "22 Adeola Odeku Street, Victoria Island" },
    highlight: "A shirt taken in today, priced per item, ready for pickup",
    catalog: [
      { name: "Wash & Fold (per kg)", category: "Wash", price: 800, cost: 250, stock: 999, reorder: 0 },
      { name: "Wash - Shirt", category: "Wash", price: 700, cost: 200, stock: 999, reorder: 0 },
      { name: "Wash - Trousers", category: "Wash", price: 900, cost: 250, stock: 999, reorder: 0 },
      { name: "Duvet/Bedspread Wash", category: "Wash", price: 4500, cost: 1400, stock: 999, reorder: 0 },
      { name: "Carpet Cleaning (per sqm)", category: "Wash", price: 1500, cost: 500, stock: 999, reorder: 0 },
      { name: "Dry Clean - Suit (2pc)", category: "Dry Clean", price: 5500, cost: 1800, stock: 999, reorder: 0 },
      { name: "Dry Clean - Native Attire", category: "Dry Clean", price: 4500, cost: 1500, stock: 999, reorder: 0 },
      { name: "Dry Clean - Gown/Dress", category: "Dry Clean", price: 6000, cost: 2000, stock: 999, reorder: 0 },
      { name: "Curtain Dry Clean (per panel)", category: "Dry Clean", price: 3500, cost: 1200, stock: 999, reorder: 0 },
      { name: "Shoe Cleaning", category: "Dry Clean", price: 2500, cost: 800, stock: 999, reorder: 0 },
      { name: "Leather Jacket Clean", category: "Dry Clean", price: 8500, cost: 3000, stock: 999, reorder: 0 },
      { name: "Iron - Shirt", category: "Iron", price: 400, cost: 100, stock: 999, reorder: 0 },
      { name: "Iron - Trousers", category: "Iron", price: 450, cost: 120, stock: 999, reorder: 0 },
      { name: "Iron - Agbada/Native", category: "Iron", price: 1200, cost: 350, stock: 999, reorder: 0 },
      { name: "Starch & Iron - Native", category: "Iron", price: 1500, cost: 450, stock: 999, reorder: 0 },
      { name: "Alteration - Hem", category: "Alterations", price: 1500, cost: 500, stock: 999, reorder: 0 },
      { name: "Alteration - Zipper Replacement", category: "Alterations", price: 2500, cost: 900, stock: 999, reorder: 0 },
      { name: "Alteration - Resize", category: "Alterations", price: 3000, cost: 1000, stock: 999, reorder: 0 },
      { name: "Pickup & Delivery", category: "Pickup & Delivery", price: 2000, cost: 600, stock: 999, reorder: 0 },
      { name: "Express Service (same day)", category: "Pickup & Delivery", price: 3000, cost: 500, stock: 999, reorder: 0 },
    ],
  },

  supermarket: {
    label: "Supermarket / Mini-Mart", group: "Retail", depth: "full",
    blurb: "Everyday groceries, priced and counted right.",
    business: "Fresh Mart Supermarket",
    branch: { name: "Main Store", address: "15 Allen Avenue, Ikeja" },
    highlight: "A full FMCG catalog with reorder levels already set",
    catalog: [
      { name: "Rice (50kg bag)", category: "Groceries", price: 78000, cost: 71000, stock: 6, reorder: 3 },
      { name: "Semovita (2kg)", category: "Groceries", price: 2200, cost: 1850, stock: 40, reorder: 15 },
      { name: "Vegetable Oil (5L)", category: "Groceries", price: 13500, cost: 11800, stock: 25, reorder: 10 },
      { name: "Spaghetti (500g)", category: "Groceries", price: 900, cost: 650, stock: 80, reorder: 30 },
      { name: "Sugar (1kg)", category: "Groceries", price: 1500, cost: 1200, stock: 50, reorder: 20 },
      { name: "Tomato Paste (tin)", category: "Groceries", price: 450, cost: 320, stock: 100, reorder: 40 },
      { name: "Bottled Water 75cl", category: "Beverages", price: 250, cost: 150, stock: 200, reorder: 80 },
      { name: "Coca-Cola 35cl", category: "Beverages", price: 400, cost: 280, stock: 150, reorder: 60 },
      { name: "Malt Drink 33cl", category: "Beverages", price: 500, cost: 380, stock: 100, reorder: 40 },
      { name: "Orange Juice 1L", category: "Beverages", price: 1800, cost: 1400, stock: 40, reorder: 15 },
      { name: "Toilet Roll (pack of 4)", category: "Household", price: 1200, cost: 900, stock: 60, reorder: 25 },
      { name: "Detergent Powder (1kg)", category: "Household", price: 1800, cost: 1400, stock: 45, reorder: 20 },
      { name: "Dish Soap (500ml)", category: "Household", price: 900, cost: 650, stock: 50, reorder: 20 },
      { name: "Insecticide Spray", category: "Household", price: 2200, cost: 1700, stock: 30, reorder: 12 },
      { name: "Toothpaste", category: "Personal Care", price: 950, cost: 700, stock: 70, reorder: 30 },
      { name: "Bathing Soap", category: "Personal Care", price: 500, cost: 350, stock: 90, reorder: 35 },
      { name: "Sanitary Pad (pack)", category: "Personal Care", price: 1100, cost: 800, stock: 40, reorder: 15 },
      { name: "Potato Chips", category: "Snacks", price: 700, cost: 450, stock: 60, reorder: 25 },
      { name: "Biscuit Pack", category: "Snacks", price: 400, cost: 280, stock: 100, reorder: 40 },
      { name: "Frozen Chicken (kg)", category: "Frozen", price: 3200, cost: 2700, stock: 30, reorder: 10, expiry: inDays(60) },
      { name: "Ice Cream Tub", category: "Frozen", price: 3500, cost: 2600, stock: 20, reorder: 8 },
    ],
  },

  gym: {
    label: "Fitness Gym", group: "Fitness & Wellness", depth: "catalog",
    pending: "Membership subscriptions are real — open Members, sell a plan and scan the card it issues at Check-In to see an active/expired membership recognised instantly. No demo member is pre-seeded, so today's catalog shows merchandise and supplements as plain stock.",
    blurb: "Members who tap in, not stock that runs out.",
    business: "IronCore Fitness Club",
    branch: { name: "Main Gym", address: "8 Admiralty Way, Lekki Phase 1" },
    highlight: "Scan a member's card at the door — active or expired, instantly",
    catalog: [
      { name: "Personal Training Session (1hr)", category: "Personal Training", price: 15000, cost: 6000, stock: 999, reorder: 0 },
      { name: "Personal Training Package (10 sessions)", category: "Personal Training", price: 120000, cost: 50000, stock: 999, reorder: 0 },
      { name: "Fitness Assessment", category: "Personal Training", price: 5000, cost: 1500, stock: 999, reorder: 0 },
      { name: "Nutrition Consultation", category: "Personal Training", price: 10000, cost: 3000, stock: 999, reorder: 0 },
      { name: "Guest Day Pass", category: "Personal Training", price: 5000, cost: 0, stock: 999, reorder: 0 },
      { name: "Gym T-Shirt", category: "Merchandise", price: 6500, cost: 3800, stock: 40, reorder: 15 },
      { name: "Gym Towel", category: "Merchandise", price: 3500, cost: 2000, stock: 50, reorder: 20 },
      { name: "Shaker Bottle", category: "Merchandise", price: 2500, cost: 1400, stock: 60, reorder: 25 },
      { name: "Gym Gloves", category: "Merchandise", price: 4500, cost: 2600, stock: 30, reorder: 12 },
      { name: "Resistance Band Set", category: "Merchandise", price: 8000, cost: 5200, stock: 25, reorder: 10 },
      { name: "Skipping Rope", category: "Merchandise", price: 3000, cost: 1800, stock: 35, reorder: 15 },
      { name: "Locker Rental (month)", category: "Merchandise", price: 3000, cost: 0, stock: 999, reorder: 0 },
      { name: "Whey Protein (1kg)", category: "Supplements", price: 25000, cost: 18000, stock: 20, reorder: 8 },
      { name: "Whey Protein (2kg)", category: "Supplements", price: 45000, cost: 33000, stock: 12, reorder: 5 },
      { name: "Creatine Monohydrate (300g)", category: "Supplements", price: 15000, cost: 10500, stock: 18, reorder: 8 },
      { name: "Pre-Workout (300g)", category: "Supplements", price: 18000, cost: 12500, stock: 15, reorder: 6 },
      { name: "BCAA (250g)", category: "Supplements", price: 14000, cost: 9800, stock: 15, reorder: 6 },
      { name: "Mass Gainer (2kg)", category: "Supplements", price: 32000, cost: 24000, stock: 10, reorder: 5 },
      { name: "Multivitamin (60 caps)", category: "Supplements", price: 8000, cost: 5500, stock: 25, reorder: 10 },
      { name: "Energy Bar (each)", category: "Supplements", price: 1200, cost: 750, stock: 80, reorder: 30 },
    ],
    // Consumed only by seedShowcase.js's gym-specific seeding (the 24h
    // sandbox deliberately leaves membership seeding out — see `pending`
    // above, same "prove it yourself" honesty as poultry/coldroom's batches).
    gymPlans: [
      { name: "Monthly", price: 25000, durationDays: 30 },
      { name: "Quarterly", price: 65000, durationDays: 90 },
      { name: "Annual", price: 220000, durationDays: 365 },
    ],
  },
};

export const DEMO_TYPES = Object.keys(DEMOS);
