// Days from today, for stock that should be nearing (or past) its date.
const inDays = (n) => new Date(Date.now() + n * 86_400_000);

/**
 * The demo shops a visitor can choose between — one per trade StarTrack is
 * pitched at, so the sandbox speaks their vocabulary from the first screen.
 * A pharmacist landing in a supermarket learns nothing about whether this
 * suits them.
 *
 * `depth` is honest about how far each one goes today:
 *   "full"    — the trade's whole workflow is implemented
 *   "catalog" — correct vocabulary, catalog, stock and alerts, but the
 *               trade-specific workflow (rooms, flocks, production runs,
 *               job tickets) is still being built. Say so rather than let
 *               someone discover it.
 */
export const DEMOS = {
  // ── Fully working today ─────────────────────────────────────────
  retail: {
    label: "Supermarket", group: "Retail & Food", depth: "full",
    blurb: "Fast lanes, full shelves, and a week of busy trading.",
    business: "Sunrise Superstore",
    branch: { name: "Main Branch", address: "12 Market Road, Lagos" },
    highlight: "Low stock alerts already waiting on two lines",
    catalog: [
      { name: "Golden Penny Semovita 2kg", category: "Grains", price: 2000, cost: 1500, stock: 42, reorder: 10, barcode: "6156000112340" },
      { name: "Honeywell Noodles (single)", category: "Grains", price: 400, cost: 290, stock: 88, reorder: 30 },
      { name: "Indomie Chicken (carton)", category: "Grains", price: 3500, cost: 2900, stock: 14, reorder: 8 },
      { name: "Peak Milk 400g", category: "Dairy", price: 1500, cost: 1150, stock: 26, reorder: 15 },
      { name: "Milo 500g", category: "Dairy", price: 2800, cost: 2250, stock: 19, reorder: 10 },
      { name: "Bournvita 900g", category: "Dairy", price: 4200, cost: 3400, stock: 9, reorder: 6 },
      { name: "Kings Oil 5L", category: "Oils", price: 7500, cost: 6300, stock: 3, reorder: 10 },
      { name: "Power Oil 3.5L", category: "Oils", price: 6200, cost: 5200, stock: 15, reorder: 8 },
      { name: "Dangote Sugar 1kg", category: "Baking", price: 900, cost: 700, stock: 5, reorder: 15 },
      { name: "Golden Penny Flour 1kg", category: "Baking", price: 1100, cost: 850, stock: 22, reorder: 12 },
      { name: "Titus Sardine", category: "Canned", price: 1200, cost: 950, stock: 31, reorder: 20 },
      { name: "Maggi Cubes (roll)", category: "Spices", price: 600, cost: 420, stock: 64, reorder: 25 },
    ],
  },

  pharmacy: {
    label: "Pharmacy", group: "Retail & Food", depth: "full",
    blurb: "Expiry-aware from day one, with dates already running down.",
    business: "Wellspring Pharmacy",
    branch: { name: "Main Dispensary", address: "8 Hospital Road, Enugu" },
    highlight: "One batch already expired, two more inside a month",
    catalog: [
      { name: "Paracetamol 500mg (card)", category: "OTC", price: 300, cost: 180, stock: 120, reorder: 40, expiry: inDays(240) },
      { name: "Amoxicillin 500mg (course)", category: "Prescription", price: 2500, cost: 1800, stock: 34, reorder: 15, expiry: inDays(120) },
      { name: "Vitamin C 1000mg", category: "Supplements", price: 1800, cost: 1250, stock: 48, reorder: 20, expiry: inDays(26) },
      { name: "Cough Syrup 100ml", category: "OTC", price: 1400, cost: 950, stock: 7, reorder: 12, expiry: inDays(5) },
      { name: "Blood Pressure Monitor", category: "Devices", price: 24000, cost: 18000, stock: 4, reorder: 3 },
      { name: "Insulin Syringes (box)", category: "Devices", price: 3200, cost: 2400, stock: 18, reorder: 10 },
      { name: "Antimalarial (ACT)", category: "Prescription", price: 3800, cost: 2900, stock: 22, reorder: 12, expiry: inDays(-6) },
      { name: "Baby Formula 400g", category: "Baby & Mother", price: 6500, cost: 5200, stock: 11, reorder: 8, expiry: inDays(95) },
      { name: "Antiseptic Liquid 250ml", category: "First Aid", price: 1600, cost: 1100, stock: 29, reorder: 15 },
      { name: "Sterile Gauze (pack)", category: "First Aid", price: 900, cost: 560, stock: 3, reorder: 20 },
      { name: "Multivitamin Syrup", category: "Supplements", price: 2200, cost: 1600, stock: 16, reorder: 10, expiry: inDays(58) },
    ],
  },

  bar: {
    label: "Bar & Lounge", group: "Retail & Food", depth: "full",
    blurb: "Every bottle accounted for, across a busy weekend.",
    business: "Sunset Lounge",
    branch: { name: "Main Bar", address: "24 Ozumba Mbadiwe, Lagos" },
    highlight: "Spirits run down after the weekend",
    catalog: [
      { name: "Star Lager (bottle)", category: "Beer", price: 1200, cost: 800, stock: 96, reorder: 48, barcode: "6154000998120" },
      { name: "Heineken (bottle)", category: "Beer", price: 1800, cost: 1250, stock: 72, reorder: 36 },
      { name: "Guinness Stout (bottle)", category: "Beer", price: 1500, cost: 1050, stock: 54, reorder: 30 },
      { name: "Hennessy VS (shot)", category: "Spirits", price: 4500, cost: 3200, stock: 6, reorder: 12 },
      { name: "Jameson (shot)", category: "Spirits", price: 3000, cost: 2100, stock: 4, reorder: 10 },
      { name: "Campari (shot)", category: "Spirits", price: 2500, cost: 1700, stock: 21, reorder: 10 },
      { name: "Four Cousins Red", category: "Wine", price: 12000, cost: 9000, stock: 9, reorder: 6 },
      { name: "Coca-Cola (bottle)", category: "Soft Drinks", price: 500, cost: 300, stock: 140, reorder: 60 },
      { name: "Chapman (glass)", category: "Soft Drinks", price: 2000, cost: 900, stock: 60, reorder: 20 },
      { name: "Peppered Gizzard", category: "Food", price: 4500, cost: 2800, stock: 24, reorder: 10 },
      { name: "Suya Platter", category: "Food", price: 6000, cost: 3600, stock: 15, reorder: 8 },
    ],
  },

  tailoring: {
    label: "Tailoring & Fashion", group: "Workshop & Trade", depth: "full",
    blurb: "Made-to-measure: fabrics priced per metre, jobs built from a recipe.",
    business: "Adaeze Couture",
    branch: { name: "Workshop", address: "5 Aba Road, Port Harcourt" },
    highlight: "Sell a custom piece and watch it eat the fabric",
    catalog: [
      { name: "Ankara Wax Print (metre)", category: "Fabrics", price: 3500, cost: 2400, stock: 60, reorder: 20 },
      { name: "Plain Cotton (metre)", category: "Fabrics", price: 2200, cost: 1500, stock: 45, reorder: 20 },
      { name: "Lace Fabric (metre)", category: "Fabrics", price: 9000, cost: 6800, stock: 12, reorder: 10 },
      { name: "Senator Material (metre)", category: "Fabrics", price: 5500, cost: 4000, stock: 8, reorder: 15 },
      { name: "Lining (metre)", category: "Fabrics", price: 900, cost: 550, stock: 80, reorder: 30 },
      { name: "Zip (piece)", category: "Accessories", price: 300, cost: 150, stock: 120, reorder: 40 },
      { name: "Buttons (card)", category: "Accessories", price: 250, cost: 120, stock: 90, reorder: 30 },
      { name: "Thread Spool", category: "Accessories", price: 400, cost: 220, stock: 55, reorder: 25 },
      { name: "Hem & Alteration", category: "Alterations", price: 2500, cost: 600, stock: 999, reorder: 0 },
      { name: "Ready-made Kaftan", category: "Sewing Jobs", price: 28000, cost: 16000, stock: 6, reorder: 4 },
    ],
    madeToOrder: {
      name: "Custom Curtains", category: "Sewing Jobs", price: 4200,
      bom: [
        { component: "Ankara Wax Print (metre)", per: "sqm", factor: 1.15 },
        { component: "Lining (metre)", per: "sqm", factor: 1 },
        { component: "Thread Spool", per: "unit", factor: 0.25 },
      ],
    },
  },

  blinds: {
    label: "Window Blinds", group: "Workshop & Trade", depth: "full",
    blurb: "Priced per square metre, cut from rail and fabric you hold in stock.",
    business: "ClearView Blinds",
    branch: { name: "Showroom", address: "31 Awolowo Way, Ikeja" },
    highlight: "A 2m × 1.5m blind consumes rail, fabric and brackets",
    catalog: [
      { name: "Blackout Fabric (metre)", category: "Fabrics", price: 4800, cost: 3200, stock: 90, reorder: 30 },
      { name: "Sheer Day Fabric (metre)", category: "Fabrics", price: 3600, cost: 2400, stock: 65, reorder: 30 },
      { name: "Aluminium Rail (metre)", category: "Tracks & Rails", price: 2500, cost: 1600, stock: 48, reorder: 20 },
      { name: "Bottom Bar (metre)", category: "Tracks & Rails", price: 1400, cost: 850, stock: 40, reorder: 20 },
      { name: "Mounting Bracket", category: "Fittings", price: 700, cost: 380, stock: 160, reorder: 60 },
      { name: "Chain & Control Set", category: "Fittings", price: 1800, cost: 1050, stock: 52, reorder: 25 },
      { name: "Vertical Blind Slat", category: "Blinds", price: 950, cost: 560, stock: 220, reorder: 80 },
      { name: "Installation (per window)", category: "Installation", price: 5000, cost: 1500, stock: 999, reorder: 0 },
      { name: "Site Measurement Visit", category: "Installation", price: 3000, cost: 800, stock: 999, reorder: 0 },
    ],
    madeToOrder: {
      name: "Roller Blind (made to size)", category: "Blinds", price: 6500,
      bom: [
        { component: "Blackout Fabric (metre)", per: "sqm", factor: 1.1 },
        { component: "Aluminium Rail (metre)", per: "width", factor: 1 },
        { component: "Bottom Bar (metre)", per: "width", factor: 1 },
        { component: "Mounting Bracket", per: "unit", factor: 2 },
        { component: "Chain & Control Set", per: "unit", factor: 1 },
      ],
    },
  },

  bakery: {
    label: "Bakery", group: "Retail & Food", depth: "full",
    blurb: "Baked this morning, gone by evening — short shelf life throughout.",
    business: "Sweet Crust Bakery",
    branch: { name: "Main Bakery", address: "17 Ogui Road, Enugu" },
    highlight: "Everything dated: today's bread expires tomorrow",
    catalog: [
      { name: "Family Loaf", category: "Bread", price: 1300, cost: 750, stock: 40, reorder: 20, expiry: inDays(2) },
      { name: "Sliced Sandwich Loaf", category: "Bread", price: 1600, cost: 950, stock: 28, reorder: 15, expiry: inDays(3) },
      { name: "Coconut Bread", category: "Bread", price: 1500, cost: 900, stock: 12, reorder: 15, expiry: inDays(2) },
      { name: "Meat Pie", category: "Pastries", price: 800, cost: 420, stock: 36, reorder: 20, expiry: inDays(1) },
      { name: "Sausage Roll", category: "Pastries", price: 600, cost: 300, stock: 44, reorder: 20, expiry: inDays(1) },
      { name: "Doughnut", category: "Pastries", price: 500, cost: 240, stock: 18, reorder: 24, expiry: inDays(1) },
      { name: "Birthday Cake (8in)", category: "Cakes", price: 18000, cost: 9500, stock: 3, reorder: 2, expiry: inDays(4) },
      { name: "Banana Bread", category: "Cakes", price: 3500, cost: 1900, stock: 9, reorder: 6, expiry: inDays(5) },
      { name: "Bottled Water 50cl", category: "Drinks", price: 200, cost: 110, stock: 120, reorder: 48 },
      { name: "Zobo Drink 50cl", category: "Drinks", price: 500, cost: 240, stock: 30, reorder: 20, expiry: inDays(6) },
    ],
  },

  electronics: {
    label: "Electronics", group: "Retail & Food", depth: "full",
    blurb: "High-value stock where a single unit matters.",
    business: "Bright Tech Store",
    branch: { name: "Main Shop", address: "3 Computer Village, Ikeja" },
    highlight: "Margins visible on every line — staff never see cost",
    catalog: [
      { name: "iPhone 13 128GB", category: "Phones", price: 620000, cost: 545000, stock: 4, reorder: 3 },
      { name: "Samsung A15", category: "Phones", price: 185000, cost: 158000, stock: 11, reorder: 5 },
      { name: "Tecno Spark 20", category: "Phones", price: 128000, cost: 108000, stock: 2, reorder: 6 },
      { name: "HP Pavilion i5", category: "Computers", price: 780000, cost: 690000, stock: 3, reorder: 2 },
      { name: "Wireless Mouse", category: "Accessories", price: 6500, cost: 3800, stock: 40, reorder: 15 },
      { name: "65W USB-C Charger", category: "Accessories", price: 12000, cost: 7200, stock: 26, reorder: 12 },
      { name: "Power Bank 20000mAh", category: "Accessories", price: 22000, cost: 14500, stock: 8, reorder: 10 },
      { name: "Bluetooth Speaker", category: "Audio & TV", price: 35000, cost: 24000, stock: 6, reorder: 4 },
      { name: "43in Smart TV", category: "Audio & TV", price: 295000, cost: 248000, stock: 2, reorder: 2 },
      { name: "Screen Replacement", category: "Repairs", price: 45000, cost: 28000, stock: 999, reorder: 0 },
    ],
  },

  // ── Catalog-accurate, workflow still being built ────────────────
  hotel: {
    label: "Hotel & Guest House", group: "Hospitality", depth: "full",
    blurb: "Rooms booked across dates, a heat map of the week, and folios that settle once.",
    business: "Palm Court Hotel",
    branch: { name: "Front Desk", address: "9 Rumuola Road, Port Harcourt" },
    highlight: "14 rooms with guests in house and arrivals due today",
    // Only things the hotel actually STOCKS. Rooms are not stock — see rooms below.
    catalog: [
      { name: "Continental Breakfast", category: "Food & Drinks", price: 6500, cost: 2800, stock: 60, reorder: 20 },
      { name: "Jollof Rice & Chicken", category: "Food & Drinks", price: 8500, cost: 3900, stock: 40, reorder: 15 },
      { name: "Club Sandwich", category: "Food & Drinks", price: 5500, cost: 2400, stock: 30, reorder: 12 },
      { name: "Bottled Water 75cl", category: "Food & Drinks", price: 700, cost: 300, stock: 180, reorder: 60 },
      { name: "Chilled Beer", category: "Food & Drinks", price: 1800, cost: 1100, stock: 96, reorder: 40 },
      { name: "Soft Drink", category: "Food & Drinks", price: 700, cost: 350, stock: 8, reorder: 40 },
      { name: "Laundry (per load)", category: "Laundry", price: 7500, cost: 2200, stock: 999, reorder: 0 },
      { name: "Airport Pickup", category: "Extras", price: 25000, cost: 12000, stock: 999, reorder: 0 },
      { name: "Extra Towels", category: "Extras", price: 2000, cost: 600, stock: 24, reorder: 10 },
    ],
    // Rooms are occupied over dates, never sold off a shelf.
    rooms: {
      types: [
        { name: "Standard", rate: 35000, capacity: 2, amenities: ["AC", "TV", "Wi-Fi"] },
        { name: "Deluxe", rate: 55000, capacity: 3, amenities: ["AC", "TV", "Wi-Fi", "Mini bar"] },
        { name: "Executive Suite", rate: 95000, capacity: 4, amenities: ["AC", "TV", "Wi-Fi", "Lounge", "Bath"] },
      ],
      // floor 1 standard, floor 2 deluxe, floor 3 suites
      list: [
        { number: "101", type: "Standard", floor: "1" },
        { number: "102", type: "Standard", floor: "1" },
        { number: "103", type: "Standard", floor: "1" },
        { number: "104", type: "Standard", floor: "1", housekeeping: "out_of_service", note: "AC unit being replaced" },
        { number: "105", type: "Standard", floor: "1" },
        { number: "106", type: "Standard", floor: "1" },
        { number: "201", type: "Deluxe", floor: "2" },
        { number: "202", type: "Deluxe", floor: "2" },
        { number: "203", type: "Deluxe", floor: "2" },
        { number: "204", type: "Deluxe", floor: "2", housekeeping: "dirty" },
        { number: "205", type: "Deluxe", floor: "2" },
        { number: "301", type: "Executive Suite", floor: "3" },
        { number: "302", type: "Executive Suite", floor: "3" },
        { number: "303", type: "Executive Suite", floor: "3" },
      ],
      // Offsets are relative to today, so the heat map always has something on it.
      stays: [
        { room: "101", guest: "Mr Chukwuma Eze", phone: "08031234567", from: -2, to: 2, status: "checked_in", extras: ["Continental Breakfast", "Chilled Beer"] },
        { room: "201", guest: "Mrs Aisha Bello", phone: "08079998888", from: -1, to: 3, status: "checked_in", extras: ["Jollof Rice & Chicken", "Laundry (per load)"] },
        { room: "301", guest: "Dr Tunde Bakare", phone: "08145556677", from: -3, to: 1, status: "checked_in", extras: ["Airport Pickup", "Club Sandwich"] },
        { room: "102", guest: "Ms Ngozi Okonkwo", phone: "08033334444", from: 0, to: 3, status: "booked" },
        { room: "202", guest: "Mr Idris Yusuf", phone: "08022221111", from: 1, to: 4, status: "booked" },
        { room: "303", guest: "Adeyemi Family", phone: "08188887777", from: 2, to: 6, status: "booked" },
        { room: "103", guest: "Mr Peter Obi", phone: "08066665555", from: -6, to: -3, status: "checked_out" },
      ],
    },
  },

  water: {
    label: "Water Factory", group: "Production", depth: "catalog",
    pending: "Production runs — raw materials in, bottles out, with yield variance — are being built. Today you get the materials and finished goods as stock.",
    blurb: "Sachets and bottles, with the raw materials they are made from.",
    business: "AquaPure Table Water",
    branch: { name: "Factory", address: "Km 4 Old Aba Road, Port Harcourt" },
    highlight: "Raw materials and finished goods side by side",
    catalog: [
      { name: "Preform 50cl (piece)", category: "Raw Materials", price: 26, cost: 22, stock: 8000, reorder: 3000 },
      { name: "Bottle Cap (piece)", category: "Raw Materials", price: 5, cost: 4, stock: 9500, reorder: 3000 },
      { name: "Shrink Label (piece)", category: "Raw Materials", price: 4, cost: 3, stock: 2100, reorder: 3000 },
      { name: "Sachet Film (roll)", category: "Raw Materials", price: 32000, cost: 27000, stock: 6, reorder: 4 },
      { name: "Treatment Chemicals (pack)", category: "Raw Materials", price: 18000, cost: 14500, stock: 3, reorder: 4 },
      { name: "Sachet Water (bag of 20)", category: "Sachets", price: 350, cost: 210, stock: 240, reorder: 100 },
      { name: "Bottled Water 50cl (pack of 12)", category: "Bottles", price: 1800, cost: 1150, stock: 96, reorder: 40 },
      { name: "Bottled Water 75cl (pack of 12)", category: "Bottles", price: 2600, cost: 1700, stock: 48, reorder: 30 },
      { name: "19L Dispenser Bottle", category: "Dispensers", price: 4500, cost: 3000, stock: 22, reorder: 15 },
      { name: "Dispenser Refill 19L", category: "Dispensers", price: 1800, cost: 900, stock: 60, reorder: 30 },
    ],
  },

  poultry: {
    label: "Poultry Farm", group: "Production", depth: "catalog",
    pending: "Flocks with daily feed, mortality and egg logs — and the feed conversion ratio they produce — are being built. Today you get feed and produce as stock.",
    blurb: "Feed, birds and eggs, with feed running low.",
    business: "Green Acres Poultry",
    branch: { name: "Farm", address: "Ilesa-Akure Road, Osun" },
    highlight: "Feed stock already below its reorder level",
    catalog: [
      { name: "Layer Mash (25kg bag)", category: "Feed", price: 19500, cost: 16800, stock: 8, reorder: 20 },
      { name: "Broiler Starter (25kg bag)", category: "Feed", price: 22000, cost: 19000, stock: 14, reorder: 20 },
      { name: "Grower Feed (25kg bag)", category: "Feed", price: 20500, cost: 17600, stock: 26, reorder: 15 },
      { name: "Crate of Eggs (30)", category: "Eggs", price: 5200, cost: 3400, stock: 88, reorder: 30, expiry: inDays(18) },
      { name: "Cracked Eggs (crate)", category: "Eggs", price: 3200, cost: 3400, stock: 6, reorder: 0, expiry: inDays(10) },
      { name: "Live Broiler (bird)", category: "Birds", price: 9500, cost: 6800, stock: 120, reorder: 40 },
      { name: "Old Layer (spent bird)", category: "Birds", price: 6500, cost: 4200, stock: 34, reorder: 0 },
      { name: "Day-old Chick", category: "Birds", price: 1400, cost: 1050, stock: 0, reorder: 100 },
      { name: "Newcastle Vaccine (vial)", category: "Medication", price: 4800, cost: 3600, stock: 5, reorder: 6, expiry: inDays(40) },
      { name: "Multivitamin Powder", category: "Medication", price: 3500, cost: 2400, stock: 11, reorder: 8, expiry: inDays(150) },
      { name: "Drinker (5L)", category: "Equipment", price: 4200, cost: 2800, stock: 18, reorder: 10 },
    ],
  },

  laundry: {
    label: "Laundry & Dry Cleaning", group: "Workshop & Trade", depth: "catalog",
    pending: "Job tickets — tagged in, tracked through each stage, collected — are the next build. Today the services price and sell normally.",
    blurb: "Services priced per item, with consumables behind them.",
    business: "FreshFold Laundry",
    branch: { name: "Main Shop", address: "22 Allen Avenue, Ikeja" },
    highlight: "Service pricing per garment",
    catalog: [
      { name: "Shirt — Wash & Iron", category: "Wash & Fold", price: 1200, cost: 350, stock: 999, reorder: 0 },
      { name: "Trousers — Wash & Iron", category: "Wash & Fold", price: 1500, cost: 420, stock: 999, reorder: 0 },
      { name: "Duvet (large)", category: "Specialty", price: 7500, cost: 2200, stock: 999, reorder: 0 },
      { name: "Agbada (full set)", category: "Dry Cleaning", price: 9000, cost: 2800, stock: 999, reorder: 0 },
      { name: "Suit (2-piece)", category: "Dry Cleaning", price: 6500, cost: 2100, stock: 999, reorder: 0 },
      { name: "Ironing only (per item)", category: "Ironing", price: 500, cost: 120, stock: 999, reorder: 0 },
      { name: "Curtain (per panel)", category: "Specialty", price: 4500, cost: 1300, stock: 999, reorder: 0 },
      { name: "Detergent (25L drum)", category: "Specialty", price: 42000, cost: 34000, stock: 2, reorder: 3 },
      { name: "Starch (5L)", category: "Specialty", price: 9500, cost: 7200, stock: 4, reorder: 4 },
      { name: "Garment Bags (100)", category: "Specialty", price: 8000, cost: 5500, stock: 6, reorder: 5 },
    ],
  },

  autorepair: {
    label: "Auto Repair", group: "Workshop & Trade", depth: "catalog",
    pending: "Job cards per vehicle — parts plus labour, with a service history by plate — are being built. Today parts and labour sell as lines.",
    blurb: "Parts and labour, priced separately like a real job card.",
    business: "Rapid Auto Works",
    branch: { name: "Workshop", address: "Km 8 Airport Road, Benin City" },
    highlight: "Labour and parts as separate, costed lines",
    catalog: [
      { name: "Engine Oil 5L (semi-synthetic)", category: "Engine", price: 24000, cost: 18500, stock: 14, reorder: 8 },
      { name: "Oil Filter", category: "Engine", price: 6500, cost: 4200, stock: 22, reorder: 12 },
      { name: "Air Filter", category: "Engine", price: 8500, cost: 5600, stock: 9, reorder: 10 },
      { name: "Brake Pads (front set)", category: "Body", price: 32000, cost: 24000, stock: 6, reorder: 6 },
      { name: "Car Battery 75Ah", category: "Electrical", price: 95000, cost: 78000, stock: 3, reorder: 3 },
      { name: "Alternator (reconditioned)", category: "Electrical", price: 78000, cost: 58000, stock: 2, reorder: 2 },
      { name: "Tyre 195/65 R15", category: "Tyres", price: 68000, cost: 54000, stock: 8, reorder: 6 },
      { name: "Wheel Balancing", category: "Labour", price: 5000, cost: 1200, stock: 999, reorder: 0 },
      { name: "Full Service (labour)", category: "Labour", price: 35000, cost: 9000, stock: 999, reorder: 0 },
      { name: "Diagnostics Scan", category: "Labour", price: 15000, cost: 2500, stock: 999, reorder: 0 },
    ],
  },

  coldroom: {
    label: "Cold Room", group: "Retail & Food", depth: "catalog",
    pending: "Selling by weight at the scale, and per-batch tracking, are being built. Today items sell per unit with expiry dates live.",
    blurb: "Frozen stock where every date matters.",
    business: "IceLine Frozen Foods",
    branch: { name: "Cold Room", address: "14 Mile 3 Market, Port Harcourt" },
    highlight: "Dated stock with two lines close to the edge",
    catalog: [
      { name: "Frozen Chicken (whole)", category: "Chicken", price: 9500, cost: 7200, stock: 40, reorder: 20, expiry: inDays(45) },
      { name: "Chicken Laps (carton)", category: "Chicken", price: 52000, cost: 44000, stock: 6, reorder: 5, expiry: inDays(30) },
      { name: "Turkey Wings (carton)", category: "Turkey", price: 68000, cost: 58000, stock: 3, reorder: 4, expiry: inDays(12) },
      { name: "Titus Fish (carton)", category: "Fish", price: 46000, cost: 39000, stock: 5, reorder: 4, expiry: inDays(8) },
      { name: "Croaker Fish (kg)", category: "Fish", price: 6500, cost: 4900, stock: 28, reorder: 15, expiry: inDays(22) },
      { name: "Beef (kg)", category: "Beef", price: 7200, cost: 5600, stock: 18, reorder: 12, expiry: inDays(20) },
      { name: "Cow Tripe (kg)", category: "Beef", price: 5200, cost: 3900, stock: 9, reorder: 10, expiry: inDays(16) },
      { name: "Ice Block (large)", category: "Ice", price: 700, cost: 250, stock: 60, reorder: 30 },
      { name: "Sausages (pack)", category: "Beef", price: 4200, cost: 3100, stock: 22, reorder: 12, expiry: inDays(35) },
    ],
  },

  filling: {
    label: "Filling Station", group: "Production", depth: "catalog",
    pending: "Pump meter readings reconciled against the cash drawer are being built. Today fuel and shop items sell by volume and unit.",
    blurb: "Fuel by the litre, plus the forecourt shop.",
    business: "Northgate Fuels",
    branch: { name: "Forecourt", address: "Zaria Road, Kaduna" },
    highlight: "Fuel priced per litre alongside shop stock",
    catalog: [
      { name: "PMS Petrol (litre)", category: "PMS", price: 1050, cost: 980, stock: 18000, reorder: 5000 },
      { name: "AGO Diesel (litre)", category: "AGO", price: 1320, cost: 1215, stock: 6400, reorder: 3000 },
      { name: "LPG Cooking Gas (kg)", category: "LPG", price: 1450, cost: 1250, stock: 820, reorder: 400 },
      { name: "Engine Oil 1L", category: "Lubricants", price: 7500, cost: 5600, stock: 36, reorder: 20 },
      { name: "Gear Oil 1L", category: "Lubricants", price: 8200, cost: 6300, stock: 12, reorder: 15 },
      { name: "Brake Fluid 500ml", category: "Lubricants", price: 3800, cost: 2600, stock: 18, reorder: 12 },
      { name: "Bottled Water 75cl", category: "Shop", price: 500, cost: 260, stock: 140, reorder: 60 },
      { name: "Soft Drink (can)", category: "Shop", price: 700, cost: 420, stock: 96, reorder: 48 },
      { name: "Biscuits (pack)", category: "Shop", price: 400, cost: 230, stock: 80, reorder: 40 },
      { name: "Car Air Freshener", category: "Shop", price: 2500, cost: 1400, stock: 24, reorder: 12 },
    ],
  },

  buildingmaterials: {
    label: "Building Materials", group: "Workshop & Trade", depth: "catalog",
    pending: "Customer credit accounts — supply now, invoice later, chase the balance — are being built. Today everything sells for immediate payment.",
    blurb: "Heavy stock sold in bulk, where one line is a day's revenue.",
    business: "Solid Base Materials",
    branch: { name: "Yard", address: "Lokoja Road, Abuja" },
    highlight: "High-value lines with thin, visible margins",
    catalog: [
      { name: "Dangote Cement (bag)", category: "Cement & Blocks", price: 9800, cost: 8900, stock: 320, reorder: 150 },
      { name: "BUA Cement (bag)", category: "Cement & Blocks", price: 9400, cost: 8600, stock: 180, reorder: 150 },
      { name: "9-inch Block", category: "Cement & Blocks", price: 850, cost: 620, stock: 1400, reorder: 500 },
      { name: "Iron Rod 12mm (length)", category: "Iron & Steel", price: 11500, cost: 10200, stock: 90, reorder: 60 },
      { name: "Iron Rod 16mm (length)", category: "Iron & Steel", price: 19800, cost: 17600, stock: 40, reorder: 50 },
      { name: "Binding Wire (roll)", category: "Iron & Steel", price: 32000, cost: 27500, stock: 8, reorder: 6 },
      { name: "Aluminium Roofing (metre)", category: "Roofing", price: 7800, cost: 6500, stock: 220, reorder: 100 },
      { name: "PVC Pipe 4in (length)", category: "Plumbing", price: 6200, cost: 4800, stock: 55, reorder: 30 },
      { name: "Emulsion Paint (20L)", category: "Paint", price: 42000, cost: 34000, stock: 12, reorder: 10 },
      { name: "Gloss Paint (4L)", category: "Paint", price: 16500, cost: 12800, stock: 6, reorder: 10 },
    ],
  },

  restaurant: {
    label: "Restaurant", group: "Hospitality", depth: "catalog",
    pending: "Recipes that deplete ingredients as dishes sell, and a kitchen order screen, are being built. Today the menu sells as items.",
    blurb: "A full menu with the kitchen's own stock behind it.",
    business: "Mama Cass Kitchen",
    branch: { name: "Main Restaurant", address: "40 Adeniran Ogunsanya, Surulere" },
    highlight: "Menu items alongside the ingredients they consume",
    catalog: [
      { name: "Jollof Rice & Chicken", category: "Mains", price: 5500, cost: 2400, stock: 60, reorder: 20 },
      { name: "Pounded Yam & Egusi", category: "Mains", price: 6500, cost: 2900, stock: 40, reorder: 15 },
      { name: "Fried Rice & Turkey", category: "Mains", price: 7000, cost: 3200, stock: 35, reorder: 15 },
      { name: "Pepper Soup (goat)", category: "Mains", price: 4500, cost: 2100, stock: 25, reorder: 10 },
      { name: "Moi Moi", category: "Sides", price: 1200, cost: 450, stock: 48, reorder: 20 },
      { name: "Plantain (side)", category: "Sides", price: 1000, cost: 380, stock: 55, reorder: 20 },
      { name: "Chapman", category: "Drinks", price: 2000, cost: 800, stock: 40, reorder: 20 },
      { name: "Bottled Water 75cl", category: "Drinks", price: 700, cost: 300, stock: 120, reorder: 48 },
      { name: "Rice (50kg bag)", category: "Mains", price: 78000, cost: 71000, stock: 4, reorder: 3 },
      { name: "Vegetable Oil (25L)", category: "Mains", price: 62000, cost: 55000, stock: 2, reorder: 3 },
      { name: "Chin Chin", category: "Desserts", price: 1500, cost: 600, stock: 30, reorder: 15, expiry: inDays(21) },
    ],
  },

  salon: {
    label: "Salon & Beauty", group: "Workshop & Trade", depth: "catalog",
    pending: "Appointments against a stylist or chair, and commission per stylist, are being built. Today services sell like any other line.",
    blurb: "Services and retail products under one till.",
    business: "Glow Beauty Studio",
    branch: { name: "Studio", address: "6 Admiralty Way, Lekki" },
    highlight: "Service revenue next to retail product margin",
    catalog: [
      { name: "Wash & Blow Dry", category: "Hair", price: 8000, cost: 1500, stock: 999, reorder: 0 },
      { name: "Braiding (full)", category: "Hair", price: 25000, cost: 6000, stock: 999, reorder: 0 },
      { name: "Relaxer Treatment", category: "Hair", price: 15000, cost: 4200, stock: 999, reorder: 0 },
      { name: "Manicure", category: "Nails", price: 7000, cost: 1400, stock: 999, reorder: 0 },
      { name: "Pedicure", category: "Nails", price: 9000, cost: 1800, stock: 999, reorder: 0 },
      { name: "Gel Nail Extension", category: "Nails", price: 18000, cost: 4500, stock: 999, reorder: 0 },
      { name: "Full Body Massage", category: "Spa", price: 30000, cost: 8000, stock: 999, reorder: 0 },
      { name: "Hair Cream 250ml", category: "Retail Products", price: 6500, cost: 4200, stock: 18, reorder: 10 },
      { name: "Edge Control", category: "Retail Products", price: 4500, cost: 2600, stock: 4, reorder: 12 },
      { name: "Human Hair Bundle", category: "Retail Products", price: 85000, cost: 62000, stock: 3, reorder: 2 },
    ],
  },
};

export const DEMO_TYPES = Object.keys(DEMOS);
