// Branded print engine — mirrors the legacy Tado Foods report look:
// blue rule under uppercase headers, zebra rows, mono numbers, totals row.
// Opens a clean window with just the report and triggers the print dialog.

export type ReportColumn<T> = {
  label: string;
  align?: "left" | "right" | "center";
  render: (row: T, index: number) => string;
};

export function printReport<T>(opts: {
  businessName: string;
  title: string;
  subtitle?: string;
  columns: ReportColumn<T>[];
  rows: T[];
  totals?: string[]; // aligned with columns; "" for blank cells
}) {
  const { businessName, title, subtitle, columns, rows, totals } = opts;
  const now = new Date().toLocaleDateString("en-NG", { day: "numeric", month: "long", year: "numeric" });
  const esc = (s: string) =>
    s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

  const th = (c: ReportColumn<T>) =>
    `<th style="padding:7px 10px;text-align:${c.align || "left"};border-bottom:2px solid #1a48cc;font-size:11px;font-weight:800;color:#1a48cc;text-transform:uppercase;letter-spacing:.6px">${esc(c.label)}</th>`;
  const td = (content: string, align: string, even: boolean, bold = false) =>
    `<td style="padding:6px 10px;font-size:12px;text-align:${align};${bold ? "font-weight:700;" : ""}color:#0a1628;background:${even ? "#ffffff" : "#f8fafd"}">${content}</td>`;

  const body = rows
    .map((row, i) => {
      const even = i % 2 === 0;
      return `<tr>${columns.map((c) => td(c.render(row, i), c.align || "left", even)).join("")}</tr>`;
    })
    .join("");

  const totalsRow = totals
    ? `<tr>${totals
        .map(
          (t, i) =>
            `<td style="padding:8px 10px;font-size:12px;font-weight:800;text-align:${columns[i]?.align || "left"};color:#0a1628;border-top:2px solid #1a48cc">${esc(t)}</td>`
        )
        .join("")}</tr>`
    : "";

  const html = `<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title></head>
<body style="font-family:'Segoe UI',system-ui,sans-serif;margin:24px;color:#0a1628">
  <div style="display:flex;align-items:baseline;justify-content:space-between;border-bottom:3px solid #1a48cc;padding-bottom:10px;margin-bottom:4px">
    <div>
      <div style="font-size:20px;font-weight:800">${esc(businessName)}</div>
      <div style="font-size:13px;font-weight:700;color:#1a48cc;margin-top:2px">${esc(title)}</div>
    </div>
    <div style="text-align:right;font-size:11px;color:#6b84af">
      ${subtitle ? esc(subtitle) + "<br>" : ""}${now}
    </div>
  </div>
  <table style="width:100%;border-collapse:collapse;margin-top:10px">
    <thead><tr>${columns.map(th).join("")}</tr></thead>
    <tbody>${body}${totalsRow}</tbody>
  </table>
  <div style="margin-top:14px;font-size:10px;color:#a8bcda">Generated by StarTrack · ${rows.length} row${rows.length === 1 ? "" : "s"}</div>
  <script>window.onload = function(){ window.print(); }<\/script>
</body></html>`;

  const w = window.open("", "_blank");
  if (!w) return;
  w.document.write(html);
  w.document.close();
}

export const mono = (s: string) => `<span style="font-family:'Courier New',monospace;font-weight:700">${s}</span>`;
